### ISSUE TITLE
Logo Design For Sleep Cycle Alarm

### ISSUE THREAD

**Issue by zularizal** [letelete/Sleep-Cycle-Alarm#24]
Hi @letelete ,  I'm a graphic designer. I have reviewed your project. You don't have a logo and icon on your app. Therefore I want to contribute to your project by creating a logo/icon, it's free for you.

Best Regards,
Zularizal

**Comment by zularizal** [comment]
Hi @letelete , I have created a logo for your app, I use material design style, what do you think?
If there is something you want to change, let me know

![bitmap](https://user-images.githubusercontent.com/38547278/45250090-98633d00-b356-11e8-82e0-aa5078078409.png)

**Comment by letelete** [comment]
Hi @zularizal, both proposals are great, but I would prefer the first one. I just have some comments to that. 

First thing first, I would like to get rid of the hour marks on the clock, because I think these are redundant and just taking too much space. It makes the logo a way too heavy.

Furthermore, I don't really like the accent color (blue). It doesn't make the logo stands out in front of the other apps in the Play Store. I would suggest to change it to `#4385f7` to make it more powerful.

**Comment by letelete** [comment]
By the way, I think that 2-color, divided parts symbolizes the cycle already, so I would love to see the first logo (with amendments - that I wrote about - included) without the cycle border. Just the clock which is inside of it. Could you make the second proposal for this idea?

**Comment by zularizal** [comment]
Sure, what do you think about these?

![2](https://user-images.githubusercontent.com/38547278/45253283-00ce1080-b38f-11e8-986d-4aa23bf2b03b.png)

**Comment by zularizal** [comment]
Hi @letelete , I have completed the logo. I have uploaded the logo vector files to the drive

https://drive.google.com/open?id=1eUG-ISGlJLr6lo_C2ADT4Balt7oTLrMl

And I have sent a pull request to you. #25
