### ISSUE TITLE
I'd like to contribute.

### ISSUE THREAD

**Issue by HarryHeights** [letelete/Sleep-Cycle-Alarm#94]
Hello, I'm Harry. I'd like to contribute to your project. I'm a content creator and copywriter. I see your project is still quite new. I could create a privacy policy document which gives details about how you deal with information collected  by the software. That's if you do collect information when the software is utilized. If you don't it's still cool to let end users know also.

If you'd like this, I'd love to get a reply from you.

**Comment by letelete** [comment]
Hello Harry, 
I like your proposal and would love to see your PR.

**Comment by HarryHeights** [comment]
Alright. I'll create the document and send a PR.

**Comment by HarryHeights** [comment]
I'd like to get some information from you though. Normally I get information I need from within the app but I see an APK file for the app is not available. I'd like to know if you collect user information when the software is used and permissions that are required for the software to work efficiently.

**Comment by letelete** [comment]
Hey, sorry for late reply. I wasn't able to answer earlier. Just because the main element of the app, the alarm service, isn't done yet I think we should hold on with the privacy policy since we're not quite sure about the end result of data collecting. I'll let you know about data collection when the app is ready.

**Comment by HarryHeights** [comment]
Yes that's a good idea. I'll wait until the software is still under development.
